#include "EnumHelperPre.h"

ENUMERATION_BEGIN(Brand)
	DECLARE_MEMBER(AUDI) DELIMITER
	DECLARE_MEMBER(CADILLAC) DELIMITER
	DECLARE_MEMBER(CHERY) DELIMITER
	DECLARE_MEMBER(CHEVROLET) DELIMITER
	DECLARE_MEMBER(CHRYSLER) DELIMITER
	DECLARE_MEMBER(CITROEN) DELIMITER
	DECLARE_MEMBER(DAEWOO) DELIMITER
	DECLARE_MEMBER(DODGE) DELIMITER
	DECLARE_MEMBER(FIAT) DELIMITER
	DECLARE_MEMBER(FORD) DELIMITER
	DECLARE_MEMBER(HONDA) DELIMITER
	DECLARE_MEMBER(HYNDAI) DELIMITER
	DECLARE_MEMBER(INFINITI) DELIMITER
	DECLARE_MEMBER(JAGUAR) DELIMITER
	DECLARE_MEMBER(KIA) DELIMITER
	DECLARE_MEMBER(LADA) DELIMITER
	DECLARE_MEMBER(LEXUS) DELIMITER
	DECLARE_MEMBER(LIFAN) DELIMITER
	DECLARE_MEMBER(MAZDA) DELIMITER
	DECLARE_MEMBER(MERCEDES) DELIMITER
	DECLARE_MEMBER(MINI) DELIMITER
	DECLARE_MEMBER(MITSUBISHI) DELIMITER
	DECLARE_MEMBER(NISSAN) DELIMITER
	DECLARE_MEMBER(OPEL) DELIMITER
	DECLARE_MEMBER(PEUGEUOT) DELIMITER
	DECLARE_MEMBER(PORSHE) DELIMITER
	DECLARE_MEMBER(RENAULT) DELIMITER
	DECLARE_MEMBER(SEAT) DELIMITER
	DECLARE_MEMBER(SKODA) DELIMITER
	DECLARE_MEMBER(SUBARU) DELIMITER
	DECLARE_MEMBER(SUZUKI) DELIMITER
	DECLARE_MEMBER(TOYOTA) DELIMITER
	DECLARE_MEMBER(VOLKSWAGEN) DELIMITER
	DECLARE_MEMBER(VOLVO) DELIMITER
	DECLARE_MEMBER(ZAZ)
ENUMERATION_END;

#include "EnumHelperPost.h"